site_name: World Economy (UAH)

theme:
  name: material

extra_css:
  - styles/extra.css

plugins:
  - search

nav:
  - "Home": index.md
  - "1. Macroeconomic variables": lesson/1-macroeconomic-variables.md
  - "1.1 National Accounts": lesson/1-1-national-accounts.md
  - "1.2 Balance of Paynments": lesson/1_2_Balance_of_payments.md
  - "2. 150 years of world economy": lesson/2_150_years.md
  - "3. Population": lesson/3_Population.md
  - "4. International Trade": lesson/4_International_Trade.md
  - "5. International Finances": lesson/5_International_Finances.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js



